### ISSUE TITLE
Shortalias for Level::vvvv

### ISSUE THREAD

**Issue by leon2225** [klenov/advancedSerial#2]
Hey,
I really like your shoartaliases, which also is the main reason I use advancedSerial.
The only problem is, that Level::vvv always takes ages to fill in, coulnd't you maybe make an alternative with just a simple int? 
Like:
`inline advancedSerial& l(int m_level) { return level(static_cast<Level>(m_level)); }`

Would be very nice:)
Leon

**Comment by klenov** [comment]
Hello Leon!
Sorry for my late reply.

I've added methods v() … vvvv() to make changing levels simpler.

So, 
`aSerial.l(Level::v)`
could be replaced with
`aSerial.v()`
